from django.urls import path

from Int_BOT_app import views

urlpatterns = [
    path('',views.LoginCode,name="LoginCode"),
    path('main1',views.main1,name="main1"),
    path('selectqus/<int:id>/<int:jid>',views.selectqus,name="selectqus"),
    path('selectqus1', views.selectqus1, name="selectqus1"),
    path('Company_Home', views.Company_Home, name="Company_Home"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('ManageJob',views.ManageJob,name="ManageJob"),
    path('ManageJobSearch',views.ManageJobSearch,name="ManageJobSearch"),
    path('JobDetail/<int:id>', views.JobDetail, name="JobDetail"),
    path('edit_job/<int:id>', views.edit_job, name="edit_job"),
    path('ViewDetails/<int:id>', views.ViewDetails, name="ViewDetails"),
    path('AddDetails', views.AddDetails, name="AddDetails"),
    path('deletejob/<int:id>', views.deletejob, name="deletejob"),
    path('AddJob', views.AddJob, name="AddJob"),
    path('ManageQnA', views.ManageQnA, name="ManageQnA"),
    path('ManageQnASearch', views.ManageQnASearch, name="ManageQnASearch"),
    path('AddQnA', views.AddQnA, name="AddQnA"),
    path('addqns', views.addqns, name="addqns"),
    path('edit_qns/<int:id>', views.edit_qns, name="edit_qns"),
    path('delete_qns/<int:id>', views.delete_qns, name="delete_qns"),
    path('editqns', views.editqns, name="editqns"),
    path('ViewRequest', views.ViewRequest, name="ViewRequest"),
    path('RequestSearch', views.RequestSearch, name="RequestSearch"),
    path('RequestAccept/<int:id>', views.RequestAccept, name="RequestAccept"),
    path('RequestReject/<int:id>', views.RequestReject, name="RequestReject"),
    path('ViewComplaint', views.ViewComplaint, name="ViewComplaint"),
    path('ComplaintSearch', views.ComplaintSearch, name="ComplaintSearch"),
    path('ComplaintReply/<int:id>', views.ComplaintReply, name="ComplaintReply"),
    path('ViewFeedback', views.ViewFeedback, name="ViewFeedback"),
   path('ViewResult', views.ViewResult, name="ViewResult"),
    path('ResultSearch', views.ResultSearch, name="ResultSearch"),
    path('ViewMore/<int:id>', views.ViewMore, name="ViewMore"),
    path('ViewProfile/<int:id>', views.ViewProfile, name="ViewProfile"),
    path('editjob', views.editjob, name="editjob"),
    path('sendreply', views.sendreply, name="sendreply"),
    path('ResultAccept/<int:id>', views.ResultAccept, name="ResultAccept"),
    path('ResultReject/<int:id>', views.ResultReject, name="ResultReject"),



    path('User_Home', views.User_Home, name="User_Home"),
    path('ViewEditProfile', views.ViewEditProfile, name="ViewEditProfile"),
    path('ViewAddEditProfile', views.ViewAddEditProfile, name="ViewAddEditProfile"),
    path('Register', views.Register, name="Register"),
    path('Register_post', views.Register_post, name="Register_post"),
    path('EditProfile', views.EditProfile, name="EditProfile"),
    path('SearchJob', views.SearchJob, name="SearchJob"),
    path('JobDetails/<int:id>', views.JobDetails, name="JobDetails"),
    path('Job_Search', views.Job_Search, name="Job_Search"),
    path('ViewRequests', views.ViewRequests, name="ViewRequests"),
    path('SearchJobRequest', views.SearchJobRequest, name="SearchJobRequest"),
    path('SendRequests/<int:id>', views.SendRequests, name="SendRequests"),
    path('ViewSelectionResult', views.ViewSelectionResult, name="ViewSelectionResult"),
    path('SearchSelectionResultJob', views.SearchSelectionResultJob, name="SearchSelectionResultJob"),
    path('SendComplaint', views.SendComplaint, name="SendComplaint"),
    path('Send_complaint', views.Send_complaint, name="Send_complaint"),
    path('ViewReply', views.ViewReply, name="ViewReply"),
    path('SendFeedback', views.SendFeedback, name="SendFeedback"),
    path('addjobs', views.addjobs, name="addjobs"),
    path('edit_details/<int:id>', views.edit_details, name="edit_details"),
    path('edited_details', views.edited_details, name="edited_details"),
    path('ViewSendFeedback', views.ViewSendFeedback, name="ViewSendFeedback"),
    path('JobDetails1', views.JobDetails1, name="JobDetails1"),

]
