# Generated by Django 4.2.7 on 2023-11-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('number_of_positions', models.BigIntegerField()),
                ('details', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QnA_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('job_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.job_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('job_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.job_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('CV', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('proof', models.FileField(upload_to='')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='result_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('emotion', models.CharField(max_length=100)),
                ('mark', models.BigIntegerField()),
                ('QnA_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.qna_table')),
                ('request_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.request_table')),
            ],
        ),
        migrations.AddField(
            model_name='request_table',
            name='user_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.user_table'),
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.BigIntegerField()),
                ('date', models.DateField()),
                ('user_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('user_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.user_table')),
            ],
        ),
    ]
