# Generated by Django 4.2.7 on 2023-11-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Int_BOT_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_table',
            name='details',
        ),
        migrations.CreateModel(
            name='job_details_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('job_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Int_BOT_app.job_table')),
            ],
        ),
    ]
