# Generated by Django 4.2.7 on 2023-12-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Int_BOT_app', '0004_result_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details_table',
            name='details',
            field=models.TextField(),
        ),
    ]
