# Generated by Django 4.2.7 on 2023-12-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Int_BOT_app', '0005_alter_job_details_table_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna_table',
            name='answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qna_table',
            name='questions',
            field=models.TextField(),
        ),
    ]
