# Generated by Django 4.2.7 on 2023-12-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Int_BOT_app', '0007_alter_result_table_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='rating',
            field=models.FloatField(),
        ),
    ]
